#!/bin/bash

SCRIPT=`realpath $0`
WORKDIR=`dirname $SCRIPT`

docker stop gravitysync
docker rm gravitysync
docker image prune -a --force
docker build -f $WORKDIR/Dockerfile $WORKDIR --tag docker_gravitysync:latest

#Copy the Dockerfile and make the appropreate modifications for arm
cp ${WORKDIR}/Dockerfile ${WORKDIR}/Dockerfile-arm
sed -i 's/alpine:3/arm64v8\/alpine/g' ${WORKDIR}/Dockerfile-arm
sed -i '0,/^FROM.*$/{s//&\nCOPY            qemu-arm-static \/usr\/bin/}' ${WORKDIR}/Dockerfile-arm
