#!/bin/bash

SCRIPT=`realpath $0`
WORKDIR=`dirname $SCRIPT`

docker stop gravitysync
docker rm gravitysync
docker image prune -a --force
docker build -f $WORKDIR/Dockerfile $WORKDIR --tag docker_gravitysync:latest
