#!/bin/bash

# The following is courtesy of the Stack Overflow Community
# https://stackoverflow.com/a/4774063
WORKDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit 1; pwd -P)"
WORKDIR=$(dirname "${WORKDIR}")
OUTPUTTYPE="docker"
REPO_OWNER="docker_"
PLATFORM="multipleplatform"
VERSION="0"

# The following is courtesy of the Stack Overflow Community
# https://stackoverflow.com/a/14203146
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        "--platform" )
            PLATFORM="$2"
            shift # past argument
            shift # past value
            ;;

        "--version" )
            VERSION="$2"
            shift # past argument
            shift # past value
            ;;

        "--push" )
            if [ "${2}" == "yes" ];
            then
                OUTPUTTYPE="registry"
                REPO_OWNER="nhmike94/"
            fi
            shift # past argument
            shift # past value
            ;;

        *)
            echo "Unknown Option"
            exit 1
        ;;
    esac
done

if [ "${VERSION}" = "0" ];
then
    echo "No version number supplied"
    exit 1
fi

# Do some checks now so if we fail we don't waste time
case ${PLATFORM}
in

    "multipleplatform" )
        BUILD_PLATFORM="linux/amd64,linux/arm64,linux/arm/v7"
        ;;
    "linux/amd64" | \
    "linux/arm64" | \
    "linux/arm/v7" )
        BUILD_PLATFORM=${PLATFORM}
        ;;

    * )
        echo "Bad Platform ${PLATFORM}"
        exit 1
        ;;
esac

if [ "${OUTPUTTYPE}" = "docker" ];
then
    echo "Forcing Platform to linux/amd64 as output type is local"
    BUILD_PLATFORM="linux/amd64"
fi

# Tidy Up
docker stop gravitysync
docker rm gravitysync
docker buildx prune -a --force

# Remove all dangling images except those specified
for r in $(docker image ls --format "{{.Repository}}" --filter "dangling=true");
do
    case ${r}
    in
        "multiarch/qemu-user-static" | \
        "moby/buildkit")
            # Do not remove these images if they exist
            ;;

        * )
            # As we are not forcefully removing, any images being used by containers will not be removed
            docker rmi "${r}" 2 &> /dev/null;
            ;;
    esac
done

# Create Builder
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name gravitysyncdockerbuilder
docker buildx use gravitysyncdockerbuilder

# Build
docker buildx build "${WORKDIR}" -f "${WORKDIR}/Dockerfile" --squash --platform "${BUILD_PLATFORM}" \
    -t "${REPO_OWNER}gravity-sync-docker:${VERSION}" -t "${REPO_OWNER}gravity-sync-docker:latest" --output=type="${OUTPUTTYPE}"

docker buildx rm gravitysyncdockerbuilder

