name: CI Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Allow Dockre-Compose to run in a non-TTY environment
        run: export COMPOSE_INTERACTIVE_NO_CLI=1
      
      - name: Bootstrap
        run: dev_scripts/bootstrap

      - name: Run Test
        run: dev_scripts/test
